        } catch (const std::invalid_argument& e) {
